//go:build generate

//go:generate go run gen_languages.go
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"slices"
)

const siteMatrixURL = "https://commons.wikimedia.org/w/api.php?action=sitematrix&smtype=language&format=json"

// Sample start of response:
//
//	{
//	  "sitematrix": {
//	    "count": 1057,
//	    "0": {
//	      "code": "aa",
//	      "name": "Qafár af",
//	      "site": [
//	        {
//	          "url": "https://aa.wikipedia.org",
//	          "dbname": "aawiki",
//	          "code": "wiki",
//	          "sitename": "Wikipedia",
//	          "closed": ""
//	        },
//	        {
//	          "url": "https://aa.wiktionary.org",
//	          "dbname": "aawiktionary",
//	          "code": "wiktionary",
//	          "sitename": "Wiktionary",
//	          "closed": ""
//	        },
//	        {
//	          "url": "https://aa.wikibooks.org",
//	          "dbname": "aawikibooks",
//	          "code": "wikibooks",
//	          "sitename": "Wikibooks",
//	          "closed": ""
//	        }
//	      ],
//	      "dir": "ltr",
//	      "localname": "Afar"
//	    },
type siteMatrixResp struct {
	SiteMatrix map[string]json.RawMessage `json:"sitematrix"`
}
type siteMatrixRespEntry struct {
	Code string `json:"code"`
}

func main() {
	req, err := http.NewRequest("GET", siteMatrixURL, nil)
	if err != nil {
		log.Fatalln(err)
	}
	req.Header.Add("User-Agent", "wt 1.0 / wiki-translate / https://github.com/alex-vit/wt")

	fmt.Println("GET", siteMatrixURL)
	httpResp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatalln(err)
	}
	defer httpResp.Body.Close()

	// bytes, err := io.ReadAll(resp.Body)
	// if err != nil {
	// 	log.Fatalln(err)
	// }
	// fmt.Println(string(bytes))

	var resp siteMatrixResp
	err = json.NewDecoder(httpResp.Body).Decode(&resp)
	if err != nil {
		log.Fatalln(err)
	}

	var languageCodes []string
	for key, rawJson := range resp.SiteMatrix {
		// skip the
		//	"count": 1049
		if key == "count" {
			continue
		}

		var entry siteMatrixRespEntry
		err := json.Unmarshal(rawJson, &entry)
		if err != nil {
			fmt.Println(err)
			continue
		}
		languageCodes = append(languageCodes, entry.Code)
	}
	slices.Sort(languageCodes)

	codesFile, err := os.OpenFile("wpcodes.txt", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		log.Fatalln(err)
	}
	defer codesFile.Close()

	var buf = bufio.NewWriter(codesFile)
	defer buf.Flush()

	_, err = buf.WriteString("// File generated by gen_languages.go; DO NOT EDIT.\n")
	if err != nil {
		log.Fatalln(err)
	}

	for _, code := range languageCodes {
		_, err = buf.WriteString(fmt.Sprintf("%s\n", code))
		if err != nil {
			log.Fatalln(err)
		}
	}

	fmt.Println("Wrote wpcodes.txt")
}
